### ISSUE TITLE
Date Issue

### ISSUE THREAD

**Issue by JLWFuQrioea69ugsykvQcg** [andrew-schofield/keepass2-passwordmodifiedcolumn#1]
Hi and thank you for creating this plugin.  I'm using version 1.01 and have some questions/issues(?).  I've read how the algorithm works and I still can't figure out how certain dates are derived for my entries.  Some seem accurate and others are way off or completely random.  Here are some examples after looking at the history entries.

1.  3/21/17 has old password, 5/9/17 has new password, plugin shows 5/31/17 (???) -- there's no history entry with 5/31/17 and today's date is 6/18/17  (random)
2.  Password has been the same since inception with the earliest history entry being 6/14/16 and the plugin shows 2/28/17, but there is no history entry with that date ( and there are many history entries but all have the same password)  (random)
3.  Some entries don't contain a password but the plugin still shows a date that doesn't fit any scenario
4.  Entry created 4/26/12, last modified on 5/5/16, no history entries, plugin shows 6/9/17 (random)
5.  Had an entry with no password, added password and saved, plugin date updated to today, opened entry and deleted password, plugin reverted back to the previous date despite the password changing twice with the history entries to show it.

Well I hope this message doesn't annoy you.  I just wanted to help. I like the concept and find it very useful.  I would like to see it continue developing.

Thanks,

Marc

**Comment by JLWFuQrioea69ugsykvQcg** [comment]
One more interesting scenario:
1.  entry created on 5/9/17, modified on 5/11/17, plugin date of 2/28/17 @ 12:11:17 PM so there are a couple of history entries but no password change.

This date appears a lot across different folders so I wonder if it's retained in memory from some other entry somehow.

**Comment by andrew-schofield** [comment]
Hi, this was more of a POC plugin to leverage some code I was already using in https://github.com/andrew-schofield/keepass2-haveibeenpwned

As it turns out Dominik (KeePass developer) actually included this functionality into KeePass 2.36, so I'd be interested in knowing how the results in the two columns compare side-by-side given they should be using basically the same algorithm. (In my testing the two are identical, and I haven't noticed the behaviour described above.)

If it's broken in this plugin, but correct in the built-in KeePass version, I'll need to fix it to make sure keepass2-haveibeenpwned works correctly.

**Comment by JLWFuQrioea69ugsykvQcg** [comment]
Oh interesting I just now realized there was a built-in column for it after I read your response.  I enabled the column and I do get different values in the fields I outlined in my post.  The built-in column appears to work correctly.
[2017-06-18_15-37-55.pdf](https://github.com/andrew-schofield/keepass2-passwordmodifiedcolumn/files/1083399/2017-06-18_15-37-55.pdf)

**Comment by andrew-schofield** [comment]
OK, I'll tweak the behaviour in the plugin to match Dominik's additions to KeePass 2.36 in case people are still using older versions.

**Comment by andrew-schofield** [comment]
I've updated the plugin to fix the broken behaviour. There were actually 2 issues.
* The algorithm didn't quite match the canonical implementation in KeePass resulting in erroneous reports of the creation date rather than the password changed date
* The column was caching the dates based on the password which caused some weird behaviour where if the passwords were the same between different entries it would result in nonsense dates being shown.
